### ISSUE TITLE
Dealer Approval email can't be rendered, even as a preview

### ISSUE THREAD

**Issue by kitsuta** [MidwestFurryFandom/mff-rams-plugin#34]
The automatic email titled "Your Midwest FurFest Dealer registration has been approved" will not send. When trying to preview it by clicking 'Examples', we get a 500 stacktrace:

```
Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 461, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 487, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 597, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 536, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/uber/uber/site_sections/emails.py", line 64, in pending_examples
    body=email.render_body(model_instance),
  File "/app/plugins/uber/uber/models/email.py", line 208, in render_body
    return self.render_template(self.body, self.renderable_data(model_instance))
  File "/app/plugins/uber/uber/models/email.py", line 214, in render_template
    return JinjaEnv.env().from_string(text).render(data)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/app/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 19, in top-level template code
  File "/app/env/lib/python3.4/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element Decimal('1')
```

At first I assumed something is wrong with the template, but it appears to throw this error even if I make the template blank.

Needs to be fixed before any dealers get approved.

**Comment by kitsuta** [comment]
Just checked this on staging, it's already been fixed by one of the many email fixes we did.
